export default {
  products: [
    {
      _id: "1",
      name: "Emerald Wave Knit Sneakers",
      category: "Women",
      image: "/images/greenwave-1.jpg",
      price: 189,
      brand: "GreenShoes Luxe",
      rating: 4.8,
      numReviews: 126,
    },
    {
      _id: "2",
      name: "Azure Tide Ocean Runners",
      category: "Women",
      image: "/images/azuretide-1.jpg",
      price: 210,
      brand: "GreenShoes Luxe",
      rating: 4.7,
      numReviews: 89,
    },
    {
      _id: "3",
      name: "Coral Reef Eco-Heels",
      category: "Women",
      image: "/images/coralreef-1.jpg",
      price: 230,
      brand: "GreenShoes Luxe",
      rating: 4.9,
      numReviews: 142,
    },
    {
      _id: "4",
      name: "Deep Sea Carbon-Lite Sneakers",
      category: "Men",
      image: "/images/deepsea-1.jpg",
      price: 175,
      brand: "GreenShoes Luxe",
      rating: 4.6,
      numReviews: 98,
    },
    {
      _id: "5",
      name: "Black Pearl Executive Loafers",
      category: "Men",
      image: "/images/blackpearl-1.jpg",
      price: 260,
      brand: "GreenShoes Luxe",
      rating: 4.8,
      numReviews: 113,
    },
    {
      _id: "6",
      name: "Tidefoam Lightweight Walkers",
      category: "Unisex",
      image: "/images/tidefoam-1.jpg",
      price: 160,
      brand: "GreenShoes Luxe",
      rating: 4.5,
      numReviews: 74,
    }
  ]
};
